<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('employees')->insert([
            [
                'staff_id'                    => 'STAFF-TEST1',
                'subsidiary'                  => 'BHF',
                'user_id'                     => null,
                'first_name'                  => 'Test',
                'middle_name'                 => 'Employee',
                'last_name'                   => 'One',
                'email'                       => 'test.employee@example.com',
                'profile_picture'             => null,
                'gender'                      => 'Male',
                'date_of_birth'               => '1990-01-01',
                'status'                      => 'Local ID',
                'religion'                    => 'Other',
                'birth_place'                 => 'Test City',
                'identification_number'       => 'ID-00000001',
                'social_security_number'      => null,
                'tax_number'                  => null,
                'passport_number'             => 'P-00000001',
                'bank_name'                   => 'Test Bank',
                'bank_branch'                 => 'Test Branch',
                'bank_account_name'           => 'Test Employee One',
                'bank_account_number'         => '0000000001',
                'office_phone'                => '1234567890',
                'mobile_phone'                => '0987654321',
                'permanent_address'           => '123 Test Street, Test City',
                'current_address'             => '123 Test Street, Test City',
                'stay_with'                   => 'Family',
                'military_status'             => false,
                'marital_status'              => 'Single',
                'spouse_name'                 => null,
                'spouse_occupation'           => null,
                'father_name'                 => 'Test Father',
                'father_occupation'           => 'Engineer',
                'mother_name'                 => 'Test Mother',
                'mother_occupation'           => 'Teacher',
                'driver_license_number'       => 'DL-00000001',
                'created_by'                  => 'Migration',
                'updated_by'                  => 'Migration',
                'created_at'                  => now(),
                'updated_at'                  => now(),
            ],
            [
                'staff_id'                    => 'STAFF-TEST2',
                'subsidiary'                  => 'SMRU',
                'user_id'                     => null,
                'first_name'                  => 'Test',
                'middle_name'                 => 'Employee',
                'last_name'                   => 'Two',
                'email'                       => 'test.employee2@example.com',
                'profile_picture'             => null,
                'gender'                      => 'Female',
                'date_of_birth'               => '1992-02-02',
                'status'                      => 'Local ID',
                'religion'                    => 'Other',
                'birth_place'                 => 'Test City',
                'identification_number'       => 'ID-00000002',
                'social_security_number'      => null,
                'tax_number'                  => null,
                'passport_number'             => 'P-00000002',
                'bank_name'                   => 'Test Bank',
                'bank_branch'                 => 'Test Branch',
                'bank_account_name'           => 'Test Employee Two',
                'bank_account_number'         => '0000000002',
                'office_phone'                => '1234567891',
                'mobile_phone'                => '0987654322',
                'permanent_address'           => '124 Test Street, Test City',
                'current_address'             => '124 Test Street, Test City',
                'stay_with'                   => 'Family',
                'military_status'             => false,
                'marital_status'              => 'Married',
                'spouse_name'                 => 'Test Spouse',
                'spouse_occupation'           => 'Doctor',
                'father_name'                 => 'Test Father Two',
                'father_occupation'           => 'Architect',
                'mother_name'                 => 'Test Mother Two',
                'mother_occupation'           => 'Nurse',
                'driver_license_number'       => 'DL-00000002',
                'created_by'                  => 'Migration',
                'updated_by'                  => 'Migration',
                'created_at'                  => now(),
                'updated_at'                  => now(),
            ],
            [
                'staff_id'                    => 'STAFF-TEST3',
                'subsidiary'                  => 'SMRU',
                'user_id'                     => null,
                'first_name'                  => 'Test',
                'middle_name'                 => 'Employee',
                'last_name'                   => 'Three',
                'email'                       => 'test.employee3@example.com',
                'profile_picture'             => null,
                'gender'                      => 'Male',
                'date_of_birth'               => '1993-03-03',
                'status'                      => 'Local ID',
                'religion'                    => 'Other',
                'birth_place'                 => 'Test City',
                'identification_number'       => 'ID-00000003',
                'social_security_number'      => null,
                'tax_number'                  => null,
                'passport_number'             => 'P-00000003',
                'bank_name'                   => 'Test Bank',
                'bank_branch'                 => 'Test Branch',
                'bank_account_name'           => 'Test Employee Three',
                'bank_account_number'         => '0000000003',
                'office_phone'                => '1234567892',
                'mobile_phone'                => '0987654323',
                'permanent_address'           => '125 Test Street, Test City',
                'current_address'             => '125 Test Street, Test City',
                'stay_with'                   => 'Alone',
                'military_status'             => true,
                'marital_status'              => 'Single',
                'spouse_name'                 => null,
                'spouse_occupation'           => null,
                'father_name'                 => 'Test Father Three',
                'father_occupation'           => 'Lawyer',
                'mother_name'                 => 'Test Mother Three',
                'mother_occupation'           => 'Professor',
                'driver_license_number'       => 'DL-00000003',
                'created_by'                  => 'Migration',
                'updated_by'                  => 'Migration',
                'created_at'                  => now(),
                'updated_at'                  => now(),
            ],
            [
                'staff_id'                    => 'STAFF-TEST4',
                'subsidiary'                  => 'BHF',
                'user_id'                     => null,
                'first_name'                  => 'Test',
                'middle_name'                 => 'Employee',
                'last_name'                   => 'Four',
                'email'                       => 'test.employee4@example.com',
                'profile_picture'             => null,
                'gender'                      => 'Female',
                'date_of_birth'               => '1994-04-04',
                'status'                      => 'Local ID',
                'religion'                    => 'Other',
                'birth_place'                 => 'Test City',
                'identification_number'       => 'ID-00000004',
                'social_security_number'      => null,
                'tax_number'                  => null,
                'passport_number'             => 'P-00000004',
                'bank_name'                   => 'Test Bank',
                'bank_branch'                 => 'Test Branch',
                'bank_account_name'           => 'Test Employee Four',
                'bank_account_number'         => '0000000004',
                'office_phone'                => '1234567893',
                'mobile_phone'                => '0987654324',
                'permanent_address'           => '126 Test Street, Test City',
                'current_address'             => '126 Test Street, Test City',
                'stay_with'                   => 'Family',
                'military_status'             => false,
                'marital_status'              => 'Divorced',
                'spouse_name'                 => null,
                'spouse_occupation'           => null,
                'father_name'                 => 'Test Father Four',
                'father_occupation'           => 'Businessman',
                'mother_name'                 => 'Test Mother Four',
                'mother_occupation'           => 'Accountant',
                'driver_license_number'       => 'DL-00000004',
                'created_by'                  => 'Migration',
                'updated_by'                  => 'Migration',
                'created_at'                  => now(),
                'updated_at'                  => now(),
            ]
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Remove the test record by matching the unique staff_id
        DB::table('employees')->where('staff_id', 'STAFF-TEST1')->delete();
    }
};
